/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoanEligibilityRouteImport } from './routes/loan-eligibility'
import { Route as EmiCalculatorRouteImport } from './routes/emi-calculator'
import { Route as CreditScoreRouteImport } from './routes/credit-score'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const LoanEligibilityRoute = LoanEligibilityRouteImport.update({
  id: '/loan-eligibility',
  path: '/loan-eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiCalculatorRoute = EmiCalculatorRouteImport.update({
  id: '/emi-calculator',
  path: '/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditScoreRoute = CreditScoreRouteImport.update({
  id: '/credit-score',
  path: '/credit-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/contact': typeof ContactRoute
  '/credit-score': typeof CreditScoreRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/loan-eligibility': typeof LoanEligibilityRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/contact': typeof ContactRoute
  '/credit-score': typeof CreditScoreRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/loan-eligibility': typeof LoanEligibilityRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/contact': typeof ContactRoute
  '/credit-score': typeof CreditScoreRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/loan-eligibility': typeof LoanEligibilityRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-advisor'
    | '/contact'
    | '/credit-score'
    | '/emi-calculator'
    | '/loan-eligibility'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-advisor'
    | '/contact'
    | '/credit-score'
    | '/emi-calculator'
    | '/loan-eligibility'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-advisor'
    | '/contact'
    | '/credit-score'
    | '/emi-calculator'
    | '/loan-eligibility'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  ContactRoute: typeof ContactRoute
  CreditScoreRoute: typeof CreditScoreRoute
  EmiCalculatorRoute: typeof EmiCalculatorRoute
  LoanEligibilityRoute: typeof LoanEligibilityRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loan-eligibility': {
      id: '/loan-eligibility'
      path: '/loan-eligibility'
      fullPath: '/loan-eligibility'
      preLoaderRoute: typeof LoanEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi-calculator': {
      id: '/emi-calculator'
      path: '/emi-calculator'
      fullPath: '/emi-calculator'
      preLoaderRoute: typeof EmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-score': {
      id: '/credit-score'
      path: '/credit-score'
      fullPath: '/credit-score'
      preLoaderRoute: typeof CreditScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  ContactRoute: ContactRoute,
  CreditScoreRoute: CreditScoreRoute,
  EmiCalculatorRoute: EmiCalculatorRoute,
  LoanEligibilityRoute: LoanEligibilityRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
